name: kaggle-m5
channels:
  - defaults
dependencies:
  - dask=2.16.0
  - ipykernel=5.1.4
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.7
  - scikit-learn=0.22.1
  - seaborn=0.10.1
  - pip:
    - catboost==0.23
    - kaggle==1.5.6
    - pandas-profiling==2.7.1
    - pygam==0.8.0
    - statsmodels==0.11.1
